config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  devise_for :users
resources :articles, :path => 'signin' do
  resources :comments
end
 
 resources :reservations
  root 'welcome#index'
  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}", as: "#{action}_page"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new 
    can :read, :all
    if user && user.admin_role?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard
    end
    if user.employee_role?
      can :manage, User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/reservation.rb
class Reservation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  def admin_role?
    ["sonnybunzz@gmail.com"].include?(email)
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  http_basic_authenticate_with name: "cmpe131", password: "cmpe131", except: [:index, :show]

  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "cmpe131", password: "cmpe131", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def menu
        render
    end
    def about
        render
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
      before_action :authenticate_user!
  http_basic_authenticate_with name: "cmpe131", password: "cmpe131", except: [:index, :show]

  def index
    @reservations = Reservation.all
  end
 
  def show
    @reservation = Reservation.find(params[:id])
  end
 
  def new
    @reservation = Reservation.new
  end
 
  def edit
    @reservation = Reservation.find(params[:id])
  end
 
  def create
    @reservation = Reservation.new(reservation_params)
 
    if @reservation.save
      redirect_to @reservation
    else
      render 'new'
    end
  end
 
  def update
    @reservation = Reservation.find(params[:id])
 
    if @reservation.update(reservation_params)
      redirect_to @reservation
    else
      render 'edit'
    end
  end
 
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
 
    redirect_to reservations_path
  end
 
  private
    def reservation_params
      params.require(:reservation).permit(:title, :text, :time)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :seats %><br>
    <%= f.text_field :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">

<%= link_to 'Sign In', new_article_path, :class => "btn btn-block btn-info", :type => "button" %>
<table class ="table table-bordered table-hover table-condensed">
  <thead>
  <tr>
    <th colspan="1">Name</th>
    <th colspan="1">Number of people</th>
    <th>Time signed in</th>
    <% if can? :manage, User %><th>Commands</th>
    <% end %>
  </tr>
  </thead>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.created_at.strftime("%B %d %Y, %l:%M%P") %></td>
      <% if can? :manage, User %>
      <td><%= link_to "Edit", edit_article_path(article), :class => "btn btn-primary btn-sm", :type => "button" %><%= button_to 'Delete', article_path(article),
              :class => "btn btn-danger btn-sm", :type => "button", method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/articles/new.html.erb
<h1>Signing In</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 

 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BEST Dining</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-default navbar-static-top" role="navigation">
				<div class="navbar-header">
					 
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button> <a class="navbar-brand" href="/">BEST</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li>
							<%= link_to 'Sign In', articles_path %>
						</li>
						<li>
							<%= link_to 'Reservations', reservations_path %>
						</li>
						<li>
							<a href="menu">Menu</a>
						</li>
						<li>
							<a href="about">About Us</a>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
					  <% if user_signed_in? %>
					  	<% if can? :manage, :all %>
					  	<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %><strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="admin">Admin CP</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<%= link_to 'Edit profile', edit_user_registration_path %>
								</li>
								<li class="divider">
								</li>
								<li>
								  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
								</li>
								</li>
							</ul>
							<% else %>
							<li class ="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= current_user.email %><strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to 'Edit profile', edit_user_registration_path %>
								</li>
								<li class="divider">
								</li>
								<li>
								  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
								</li>
								<% end %>
								</ul>
							<% else %>
							
							<li>
							  <%= link_to "Sign up", new_user_registration_path %>
							</li>
							<li>
							  <%= link_to "Login", new_user_session_path %>
							</li>
						</li>
						<% end %>
					</ul>
				</div>
				
			</nav>
		</div>
	</div>
</div>
  </head>

  <body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
    

  </body>
</html>

app/views/pages/about.html.erb
<center><h1>About Us</h1></center>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
		    <p><b>The Engineers: Sonny Banh, Peijmon Kasravi, Nicholas Mangoba, Branden Caasi</b></p>
		    <p>We started this project because we've always had problems with seating at restaurants. We wanted to try to revolutionize things by making things simple. So we created BEST Dining.</p>
		 </div>
	</div>
</div>

app/views/pages/menu.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
		    <center><img alt="menu" src="http://imgur.com/WuAw3hj.png" /></center>
		    </div>
	</div>
</div>

app/views/reservations/edit.html.erb
<h1>Editting</h1>

<%= form_for @reservation do |f| %>
 
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reservation.errors.count, "error") %> prohibited
        this reservation from being saved:
      </h2>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :seats %><br>
    <%= f.text_field :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">

<%= link_to 'Reserve', new_reservation_path, :class => "btn btn-block btn-info", :type => "button" %>
<% if can? :manage, User %>
<table class ="table table-bordered table-hover table-condensed">
  <thead>
  <tr>
    <th colspan="1">Name</th>
    <th colspan="1">Number of people</th>
    <th>Time requested</th>
    <th>Time registered</th>
    <% if can? :manage, User %><th>Commands</th>
    <% end %>
  </tr>
  </thead>
 
  <% @reservations.each do |reservation| %>
    <tr>
      <td><%= reservation.title %></td>
      <td><%= reservation.text %></td>
      <td><%= reservation.time %></td>
      <td><%= reservation.created_at.strftime("%B %d %Y, %l:%M%P") %></td>
      <% if can? :manage, User %>
      <td><%= link_to "Edit", edit_reservation_path(reservation), :class => "btn btn-primary btn-sm", :type => "button" %><%= button_to 'Delete', reservation_path(reservation),
              :class => "btn btn-danger btn-sm", :type => "button", method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  <% end %>
</table>
</div>
</div>

app/views/reservations/new.html.erb
<%= form_for @reservation do |f| %>
 
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reservation.errors.count, "error") %> prohibited
        this reservation from being saved:
      </h2>
      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :seats %><br>
    <%= f.text_field :text %>
  </p>
  
  <p>
      <%= f.label :time %><br>
      <%= f.text_field :time %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/reservations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @reservation.title %>
</p>
 
<p>
  <strong>Seats:</strong>
  <%= @reservation.text %>
</p>

<p>
    <strong>Time:</strong>
    <%= @reservation.time %>
</p>
 

 

<%= link_to 'Back', reservations_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="carousel slide" id="carousel-742681">
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#carousel-742681">
					</li>
					<li data-slide-to="1" data-target="#carousel-742681">
					</li>
					<li data-slide-to="2" data-target="#carousel-742681">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item active">
						<img alt="Carousel Bootstrap First" src="http://wallpapersdsc.net/wp-content/uploads/2016/09/Junk-Food-HD-Background.jpg" />
						<div class="carousel-caption">
						</div>
					</div>
					<div class="item">
						<img alt="Carousel Bootstrap Second" src="http://www.magic4walls.com/wp-content/uploads/2013/12/dessert-sweet-table-food-hd-wallpaper.jpg" />
						<div class="carousel-caption">
						</div>
					</div>
					<div class="item">
						<img alt="Carousel Bootstrap Third" src="http://www.freestockphotos.name/wallpaper-original/wallpapers/italian-food-2322.jpg" />
						<div class="carousel-caption">
						</div>
					</div>
				</div> <a class="left carousel-control" href="#carousel-742681" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-742681" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
			</div>
		</div>
	</div>
</div>